#!/bin/bash

. ../config.ini

apt-get update -y
apt-get dist-upgrade -y

apt-get install -y mc htop git screen
apt-get install -y libbluetooth-dev bluez-tools bluez-firmware
apt-get install -y libcrypto++-dev
apt-get install -y flite1-dev libspeechd-dev
apt-get install -y libffms2-dev
apt-get install -y libgstreamer1.0-dev libgstreamermm-1.0-dev libavcodec-extra58 libecore-audio1 
apt-get install -y libpulse-dev
apt-get install -y libmariadb-dev libpqxx-dev libpq-dev
apt-get install -y libre2-dev
apt-get install -y libicu-dev
apt-get install -y libwebp-dev
apt-get install -y libopus-dev
apt-get install -y libavcodec-dev libavdevice-dev libdlna-dev libavfilter-dev libavformat-dev libavutil-dev libffmpegthumbnailer-dev libffms2-dev libpostproc-dev libqtav-dev libqtav-private-dev libsdl-kitchensink-dev libswresample-dev libswscale-dev
apt-get install -y libvpx-dev
apt-get install -y libsnappy-dev
apt-get install -y libglib2.0-dev
apt-get install -y libzzip-dev zlib1g-dev libminizip-dev
apt-get install -y libevent-dev
apt-get install -y libxml2-dev libxslt1-dev
apt-get install -y liblcms2-dev
apt-get install -y lib ibpng-dev  ibpng++-dev libpnglite-dev
apt-get install -y libjpeg-dev
apt-get install -y libharfbuzz-dev
apt-get install -y libfreetype-dev
apt-get install -y libpci-dev

apt-get install -y libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev  libxfixes-dev
apt-get install -y libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev
apt-get install -y libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev
apt-get install -y libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev
apt-get install -y libcups2-dev

apt-get install -y libmd4c-dev libb2-dev
apt-get install -y libinput-dev libts-dev libmtdev-dev mtdev-tools
apt-get install -y libmd4c-html0-dev
