#!/bin/bash

. ../config.ini

echo " =========================================== "
echo " HYPERBORG QT CONFIGURATION SCRIPT FOR LINUX "
echo " =========================================== "
echo " Qt version:   " $QTVER
echo " Qt directory: " $QT_ROOT

cd $QT_ROOT
cd qt6
rm CMakeCache.txt

./configure -prefix /usr/local/QT-$QTVER \
    -skip qtwebengine \
    -skip qtopcua

echo " === SCRIPT ENDED ==="