#!/bin/bash

. ../config.ini

echo " ========================================= "
echo " HYPERBORG QT COMPILATION SCRIPT FOR LINUX "
echo " ========================================= "
echo " Qt version:  " $QTVER
echo " Qt directory:" $QT_DIR

cd $QT_DIR
cd qt6
cmake --build . --parallel

echo " === SCRIPT ENDED ==="
