#!/bin/bash

. ../config.ini

echo " ======================================= "
echo " HYPERBORG QT RETRIEVAL SCRIPT FOR LINUX "
echo " ======================================= "
echo " Qt version:  " $QTVER
echo " Qt directory:" $QT_ROOT

cd $QT_ROOT
cd qt6

cmake --install .

echo " === SCRIPT ENDED ==="