#!/bin/bash

. ../config.ini

export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

rm qt6 -rf
git clone https://code.qt.io/qt/qt5.git qt6
cd qt6
git checkout $QTVER

perl init-repository -f --module-subset=default
cd ..



