#!/bin/bash

. ../config.ini

cd $CMAKE_ROOT

wget http://github.com/Kitware/CMake/releases/download/v$CMAKEVER/cmake-$CMAKEVER.tar.gz

tar -xvf cmake-$CMAKEVER.tar.gz
rm cmake
ln -s cmake-$CMAKEVER cmake

cd cmake
./configure
time gmake -j
sudo gmake install