#!/bin/bash

echo "=== HYPERBORG CMAKE SCRIPT ==="

. ../config.ini

cd $CMAKE_ROOT

wget http://github.com/Kitware/CMake/releases/download/v$CMAKEVER/cmake-$CMAKEVER.tar.gz

tar -xvf cmake-$CMAKEVER.tar.gz
rm cmake
ln -s cmake-$CMAKEVER cmake

cd cmake
./configure

# Limiting compilation for 6 CPUs, higher CPU settings locked out test server (this could 
# be only our problem, feel free to increase or remove the number

time gmake -j 6
sudo gmake install

echo "=== HYPERBORG CMAKE SCRIPT ENDED ==="
