== REGISTER DEFINITIONS ==

DATE_TIME,          RW, U32, NA,    1,   40000, 2, "Epoch seconds UTC"
CITY,               RW, U32, NA,    1,   40002, 2, ""
DST,                RW, U16, NA,    1,   40004, 1, "Daylight saving time: 0: disabled, 1: enabled"
TIMEZONE,           RO, I32, "s",   1,   40005, 2, "Time zone offset measured in seconds"
DST_STATE,          RO, U16, NA,    1,   40007, 1, "0: DST time not entered, 1: DST time entered"
DST_OFFSET,         RO, U16, "mins",1,   40008, 1, "DST time offset in minutes"
LOCAL_TIME,         RO, U32, NA,    1,   40009, 2, "Epoch seconds, local time of the SmartLogger"
POWER_ON,           WO, U16, NA,    1,   40200, 1, "The data field can only be 0 for powering on all inverters"
POWER_OFF,          WO, U16, NA,    1,   40201, 1, "The data field can only be 0 for powering off all inverters"
POWER_1,            WO, U16, NA,    1,   40202, 1, "0: Power off all inverters, 1: power on all inverters"
POWER_2,            WO, U16, NA,    1,   40203, 1, "0: Power on all inverters, 1: power off all inverters"
TRANSFER_TRIP,      RW, U16, NA,    1,   40204, 1, "0: Run, 1 Fault outage -> The device shuts down when it stops due to faults and does not respond to the startup request"
ARRAY_RESET,        WO, U16, NA,    1,   40205, 1, "The data domain can only be 0" 
ACTIVE_ADJUSTMENT_DISCARDING,   RW, U32, "kW",  10,  40420, 2, "Adjusts the total active output power of all inverters connected to the SmartLogger. The adjustment value that is beyond the range is discarded"
REACTIVE_ADJUSTMENT_DISCARDING, RW, I32, "kVar",10,  40422, 2, "Adjusts the total reactive output power of all inverters connected to the SmartLogger. The adjustment value that is beyond the range is discarded"
ADJUSTMENT_DISCARDING, RW, U32, "kW", 10, 40424, 2, "Adjusts the total active output power of all inverters connected to the SmartLogger."
ADJUSTMENT_DISCARDING, RW, I32, "kVar", 10, 40426, 2, "Adjusts the total reactive output power of all inverters connected to the SmartLogger."
ACTIVE_POWER_BY_PERCENT, RW, U16, "%", 10, 40428, 1, "Adjusts the total active output power of all inverters connected to the SmartLogger. The percentage range is 0-100%"
POWER_FACTOR,   RW, I16, NA, 1000, 40429, 1, "Adjusts the total reactive output power of all inverters connected to the SmartLogger. The range is (-1, -0.8]U[0.8, 1]"
DC_CURRENT, RO, I16, "A", 10, 40500, 1, "Equals the total input DC current of all inverters. If the value exceeds the range specified by I16, register 40554 is recommended"
INPUT_POWER, RO, U32, "kW", 1000, 40521, 2, "Equals the total input power of all inverters"
CO2_REDUCTION, RO, U32, "kg", 10, 40523, 2, "Equals the total CO2 reduction of all inverters. If the value exceeds the range specified by U32, register 40550 is recommended"
ACTIVE_POWER, RO, I32, 'kW', 1000, 40525, 2, "Equals the total active output power of all inverters"
POWER_FACTOR, RO, I16, NA, 1000, 40532, "Equals the total power factor of all inverters"
PLANT_STATUS, RO, U16, NA, 1, 40543, "Used by Qinghai, 1-unlimited power, 2- limiter power operation, 3-Idle, 4-Outage, 5-Communication interrupt"
REACTIVE_POWER, RO, I32, "kVar", 1000, 40544, 2, "Equals the total reactive output power of all inverters"
CO2_REDUCTION_LARGE, RO, U64, "kg", 100, 40550, 4, "Equals the total CO2 reduction of all inverters. This register represents a larger value range compared with egister 40523"
DC_CURRENT_LARGE, RO, I32, "A", 10, 40554, 2 "Equals the total input DC current of all inverters. This register represents a larger value range compared with register 40500"
E_TOTAL, RO, U32, "kWh", 10, 40560, 2, "Equals the total energy yield generated by all inverters"
E_DAILY, RO, U32, "kWh", 10, 40562, 2, "Equals dailyenergy yield generated by all inverters"
E_DAILY_DURATION, RO, U32, "h", 10, 40564, 2, ""
PLANT_STATUS_2, RO, U16, NA, 1, 40566, 1, "Used by Xinjiang 0-idle, 1-on-grid, 2:on gird-sellf derating, 3: on-grif powerlimit, 4: planned outage, 5: power limit outage, 6: falt outage, 7: communication interrupt"
PLANT_STATUS_3, RO, U16, NA, 1, 40567, 1, "Used by Ningxia 1: on-grid,2: Outage, 3: Maintenance, 4:IDle"
ACTIVE_ALARM_SEQ, RO, U32, NA, 1, 40568, 2, ""
HISTORIC_ALARM_SEQ, RO, U32, NA, 1, 40570 2, ""
PHASE_A_CURRENT, RO, I16, "A", 1, 40572, 1, "Equals the sum of phase A currents of all inverters"
PHASE_B_CURRENT, RO, I16, "A", 1, 40573, 1, "Equals the sum of phase B currents of all inverters"
PHASE_C_CURRENT, RO, I16, "A", 1, 40574, 1, "Equals the sum of phase C currents of all inverters"
U_ab, RO, U16, "V", 10, 40575, 1, ""
U_bc, RO, U16, "V", 10, 40576, 1, ""
U_ca, RO, U16, "V", 10, 40577, 1, ""
RESERVED, RO, U16, NA, 1, 40608, 10, ""
INVERTER_EFFICIENCY, RO, U16, "%", 100, 40685, 1, ""
MAX_REACTIVE_ADJ, RO, U32, "kVar", 10, 40693, 2, "Equals the total maximum power of all inverters connected in parallel multiplied by 60%"
MIN_REACTIVE_ADJ, RO, I32, "kVar", 10, 40695, 2, "Equals the total maximum power of all inverters connected in parallel multiplied by 60%x(-1)"
MAX_ADJUSTMENT, RO, U32, "kW", 10, 40697, 2, "EQUALS the total maximum power of all inverters connected in parallel"
LOCKED, RO, U16, NA, 1, 40699, 1, "0 - locked, 1 - unlocked  If more than one inverter is on-grid and feeding power to the grid, the status is Unlocked"
DI_STATUS, RO, U16, NA, 1, 40700, 1, "Bit0: DI1 ... Bit7: DI8  1:Closed, 0: Open  Equals the status of the eight DIs of the SmartLogger"
ESN, RO, STR, NA, 1, 40713, 10, ""
SYSTEM_RESET. WO, U16, N/A, 1, 40723, 1, "Resets the SmartLogger. The data domain is not checked"
FAST_DEVICE_ACCESS, WO, U16, NA, 1, 40724, 1, "Automatically allocates and searches for devices"
DEVICE_OPERATION, WO, MLD, NA, 1, 40725, 11, "First 10 registers: determine the device to be operated based on the ESN. The register content is the device ESN. Last register: If the operation type is 0, the SmartLogger deletes inverters. If the operation type is 1 the inverter alarm is rester on the SmartLogger side"
DEVICE_ACCESS_STATUS, RO, U16, NA, 1, 40736, 1, "0: Search completed, 1: Search in progress, 2: Search failed"
ACTIVE_POWER_CONTROL_MODE, RO, U16, NA, 1, 40737, 1, "0: No limit, 1: DI active scheduling, 3: Percentage fixed-value limitation (open loop) 4: remote scheduling, 6: Export limitation (kW), 200: remote output control, 65533: Slave SmartLogger, 65534: no scheduling"
ACTIVE_POWER_SCHEDULING_TARGET, RO, U32, "kW", 10, 40738, 2, "Target total active power for the SmartLogger active power scheduling"
REACTIVE_POWER_CONTROL_MODE, RO, U16, NA, 1, 40740, 1, "0: No output, 1: DI reactive schedulong, 2: Reactive power fix control 3: Power factor fix control 4: Q-U characteristic curve, 5: cos(Phi)-P/Pn characteristic curve, 6: Q-U hysteresis curve (CEI0-16), 7: Remote scheduling, 9: Power factor closed-loop control (old policy) 10: Power factor closed-loop control 65533: Slave SmartLogger 65534: no scheduling"
REACTIVE_POWER_SCHEDULING_CURVE, RO, U16, NA, 1, 40741, 1, "0: indicated the power factor, 1: indicates the reactive power fixed value"
REACTIVE_POWER_SCHEDULING_TARGET, RO, I32, "kVar", 10/1000, 40742, 2, "SmartLogger reactive power adjustment target value: power factor or total reactive power, The specific meaning depends ont the reactive power scheduling mode. When the modse is the power factor, the gain is 1000. When the mode is reactive ppwer fixed value, the gain is 10."
ACTIVE_SCEDULING_PERCENTAGE, RO, U32, "%", 1, 40802, 2, "[0,100]"
CO2_EMISSION_REDUCTION_COEDD, RW, U16, "kg/kWh", 1000, 41124, 1, "[0,10]"
PV_MODULE_CAPACITY, RO, U32, "kW", 1000, 41934, 2, "[0,2000000]"
RATED_PLANT_CAPACITY, RO, U32, "kW", 1000, 41936, 2, ""
TOTAL_RATED_PLANT_CAPACITY, RO, U32, "kW", 1000, 41938, 2, ""
CONVERSION_COEFF, RO, U32, NA, 1000, 41940, 2, ""
COMMUNICATION_STATUS, RO, U16, NA, 1, 41942, "Status of communication between the SmartLogger and the servers of Japanese power companies: 0: connection success, 1: connection failed"
COMMUNICATION_ABRNORMAL_SHUTDOWN, RW, U16, NA, NA, 41947, 1, "0: disable, 1: enable"
COMMUNICATION_ABNORMAL_DETECTION_TIME, RW, U16, "s", NA, 41948, 1, "[60, 1800]"
AUTO_START_UPON_COMMUNICATION_RECOVERY, RW, U16, NA, NA, 41949, 1, "0: disable, 1: enable"
SYSTIME_YEAR, RW, U16, NA, 1, 42017, 1, "2000-2068 (local time)"
SYSTIME_MONTH, RW, U16, NA, 1, 42018, 1, "1-12"
SYSTIME_DAY, RW, U16, NA, 1, 42019, 1, "1-31"
SYSTIME_HOUR, RW, U16, NA, 1, 42020, 1, "0-23"
SYSTIME_MINUTE, RW, U16, NA, 1, 42021, 1, "0-59"
SYSTIME_SECOND, RW, U16, NA, 1, 42022, 1, "0-59"
CURRENT_ERROR_DURING_SCANNING, RW, U16, NA, 100, 42150, 1, "[0~2]"
INSPECTION, WO, U16, NA, 1, 42730, 1, "00: start, 01: Stop"
IV_CURVE_SCANNING, WO, U16, NA, 1, 42779, 1, "00: Stop, 01: Stat (64 points), 02: Start (128 points), 03: Start (256 points)"
ALARM_INFO_1, RO, U16, NA, 1, 50000, 1, ""
ALARM_INFO_2, RO, U16, NA, 1, 50001, 1, ""

== ALARM DEFINITIONS ==
ABNORMAL_ACTIVE_SCHEDULE, 1100, 4, MAJOR, 50000, 3, "If active Power Control Mode is set to Dry contact remote control,the four DI ports read instruction combinations not configured"
ABNORMAL_REACTIVE_SCHEDULE, 1101, 4, MAJOR, 50000, 11, "If Reactive Power Control Mode is set to Dry contact remote control, the four DI ports read instruction combinations not configured"
MCB_DISCONNECT, 1103, 1, MAJOR, 50001, 1, "The general AC circuit breaker at the grid-tied point is OFF."
ABNORMAL_CUBICLE, 1104, 1, MAJOR, 50001, 2, "The Cubicle device has detected an exception at the grid-tied point"
DEVICE_ADDRESS_CONFLICT, 1105, 1, MAJOR, 50001, 3, "The address set on the SmartLogger conflicts with an existing access decive address"
AC_SPD_FAULT, 1106, 1, NAJOR, 50001, 4, "Communication box SPD fault"
DI1_CUSTOM_ALARM, 1107, 1, ADAPTABLE, 50001, 5, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI2_CUSTOM_ALARM, 1108, 1, ADAPTABLE, 50001, 6, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI3_CUSTOM_ALARM, 1109, 1, ADAPTABLE, 50001, 7, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI4_CUSTOM_ALARM, 1110, 1, ADAPTABLE, 50001, 8, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI5_CUSTOM_ALARM, 1111, 1, ADAPTABLE, 50001, 9, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI6_CUSTOM_ALARM, 1112, 1, ADAPTABLE, 50001, 10, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI7_CUSTOM_ALARM, 1113, 1, ADAPTABLE, 50001, 11, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
DI8_CUSTOM_ALARM, 1114, 1, ADAPTABLE, 50001, 12, "The dry contact signal from the peripheral to the corresponding DI port on the SmartLogger is abnormal"
24V_POWER_FAILURE, 1115, 1, MAJOR, 50001, 13, "Communication box 24V power failure"
WEBUI_SERVER_CERT_INVALID, 1116, 1, WARNING, 50002, 0, "WebUI server certificate invalid"
WEBUI_SERVER_CERT_EXPIRES, 1117, 1, WARNING, 50002, 1, "WebUI server certificate is about to expire"
WEBUI_SERVER_CERT_EXPIRED, 1118, 1, WARNING, 50002, 2, "WebUI server certificate has expired"
LICENSE_EXPIRED, 1119, 1, WARNING, 50001, 14, "1. The privilege certificate has entered grace period. 2. The privilege feature will be invalid soon"
MANAGEMENT_CERT_INVALID, 1120, 1, WARNING, 50002, 3, "The management system certificate is not yet valid"
MANAGEMENT_CERT_EXPIRES, 1121, 1, WARNING, 50002, 4, "The management system certificate is about to expire"
MANAGEMENT_CERT_EXPIRED, 1122, 1, MAJOR, 50002, 5, "The management system certificate has expired"
REMOTEC_CERT_INVALID, 1123, 1, WARNING, 50002, 6, "The remote output control certificate is not yet valid"
REMOTEC_CERT_EXPIRES, 1124, 1, WARNING, 50002, 7, "The remote output control system certificate is about to expire"
REMOTED_CERT_EXPIRED, 1125, 1, MAJOR, 50002, 8, "The remote output control system certificate has expired"
ESGCC_CERT_INVALID, 1126, 1, WARNING, 50002, 9, "The poverty alleviation monitoring center certificate is not yet valid"
ESGCC_CERT_EXPIRES, 1127, 1, WARNING, 50002, 10, "The poverty alleviation monitoring center certificate is about to expire"
ESGCC_CERT_EXPIRED, 1128, 1, MAJOR, 50002, 11, "The poverty alleviation monitoring center certificate has expired"
SMARTLOGGER_CERT_INVALID, 1129, 1, WARNING, 50002, 12, "The SmartLogger certificate is not yet valid"
SMARTLOGGER_CERT_EXPIRES, 1130, 1, WARNING, 50002, 13, "The SmartLogger certificate is about to expire"
SMARTLOGGER_CERT_EXPIRED, 1131, 1, MAJOR, 50002, 114, "The SmartLogger certificate has expired"

== Register for the environmental montiro instrument

WIND_SPEED, RO, I16, "m/s", 10, 40031, 1
WIND_DIRECTION, RO, I16, "°", 1, 40032, 1
PV_MODULE_TEMP, RO, I16, "°C", 10, 40033, 1
AMBIENT_TEMPERATURE, RO, I16, "°C", 10, 40034, 1
TOTAL_IRRADIANCE, RO, I16, "W/m2", 10, 40035, 1
DAILY_IRRADIATION, RO, U32, "MJ/m2", 1000, 40036, 2
TOTAL_IRRADIANCE_2, RO. I16, "W/m2", 10, 40038, 1
DAILY_IRRADIATION, RO, U32, "MJ/m2", 1000, 40039, 2
CUSTOM_1, RO, I16, NA, 10, 40041, 1
CUSTOM_2, RO, I16, NA, 10, 40042, 1
DAILY_IRRADIATION_AMOUNT, RO, U32, "kWh/m2", 10000, 40043, 2
DAILY_IRRADIATION_AMOUNT_1, RO, U32, "kWh/m2", 10000, 400435, 2

== Registers for the Power Meter ==

PHASE_A_VOLTAGE, RO, U32, "V", 100, 32260, 2
PHASE_B_VOLTAGE, RO, U32, "V", 100, 32262, 2
PHASE_C_VOLTAGE, RO, U32, "V", 100, 32264, 2
AB_LINE_VOLTAGE, RO, U32, "V", 100, 32266, 2
BC_LINE_VOLTAGE, RO, U32, "V", 100, 32268, 2
CA_LINE_VOLTAGE, RO, U32, "V", 100, 32270, 2
PHASE_A_CURRENT, RO, U32, "A", 10, 32272, 2
PHASE_B_CURRENT, RO, U32, "A", 10, 32274, 2
PHASE_C_CURRENT, RO, U32, "A", 10, 32276, 2
ACTIVE_POWER, RO, I32, "kW", 1000, 32278, 2
REACTIVE_POWER, RO, I32, "kVar", 1000, 32280, 2
ACTIVE_ELECTRICITY, RO, I32, "kWh", 10, 32282, 2
POWER_FACTOR, RO, I16, NA, 1000, 32284, 1
REACTIVE_ELECTRICITY, RO, I32, "kvarh", 10, 32285, 2
APPARENT_POWER, RO, I32, "kVA", 1000, 32287, 2
POSITIVE_ACTIVE_ELECTRICITY, RO, I32, "kWh", 100, 32289, 2
POSITIVE_REACTIVE_ELECTRICITY, RO, I32, "kvarh", 100, 32291, 2
????

== PUBLIC REGISTER DEFINITIONS ==
DEVICE_LIST_CHANGE_NUMBER, RO, U16, NA, 1, 65521, 1, ""
POER_NUMBER, RO, U16, NA, 1, 65522, 1, ""
DEVICE_ADDRESS, RO, U16, NA, 1, 65523, 1, ""
DEVICE_NAME, RW, STR, NA, 1, 65524, 10, ""
DEVICE_CONNECTION_STATUS, RO, U16, NA, 1, 65534, 1, "0xB000: disconnection, 0xb001: online"









