#!/bin/bash

export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
. ../config.ini

echo "HYPERBORG EMSDK ACTIVATION SCRIPT starts"
echo "EMSDK ROOT: " $EMSDK_ROOT
echo "EMSDK VER : " $EMSDKVER

cd $EMSDK_ROOT

# Get the emsdk repo
rm -rf $EMSDKVER
git clone https://github.com/emscripten-core/emsdk.git $EMSDKVER
rm active
ln -s $EMSDKVER active

cd $EMSDKVER
git pull
./emsdk install $EMSDKVER
./emsdk activate $EMSDKVER

echo "HYPERBORG EMSDK ACTIVATION SCRIPT ends"
